# --- Install OpenLDAP ---
- name: Install OpenLDAP packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: 
    - openldap
    - openldap-servers
    - openldap-clients

# --- Ensure slapd is running ---
- name: Ensure slapd service is started and enabled
  ansible.builtin.service:
    name: slapd
    state: started
    enabled: yes

# --- Temporary directory ---
- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: /tmp
    state: directory

# --- Step 1: Add baseDN (must exist before RootDN config) ---
- name: Render basedn.ldif
  ansible.builtin.copy:
    dest: /tmp/basedn.ldif
    content: |
      dn: {{ ldap_basedn }}
      objectClass: top
      objectClass: dcObject
      objectClass: organization
      o: Hadoop Test
      dc: hadoop

      dn: {{ ldap_rootdn }}
      objectClass: organizationalRole
      cn: Manager
      description: Directory Manager

- name: Add baseDN entry to LDAP
  ansible.builtin.command: >
    ldapadd -x -D "{{ ldap_rootdn }}" -w "{{ ldap_rootpw }}"
    -H ldap://localhost -f /tmp/basedn.ldif
  register: add_basedn
  failed_when: add_basedn.rc != 0 and "Already exists" not in add_basedn.stderr

# --- Step 2: Configure RootDN in cn=config ---
- name: Render configure-rootdn.ldif
  ansible.builtin.template:
    src: configure-rootdn.ldif.j2
    dest: /tmp/configure-rootdn.ldif

- name: Apply RootDN config
  ansible.builtin.command: >
    ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/configure-rootdn.ldif
  register: rootdn_config
  failed_when: rootdn_config.rc != 0 and "Already exists" not in rootdn_config.stderr